### ISSUE TITLE
###json parsing issue

### ISSUE THREAD

**Issue by deb-anndy** [mukeshsolanki/Places-AutoComplete-EditText#14]
org.json.JSONException: No value for plus_code

remove plus_code

**Comment by Crymzix** [comment]
> org.json.JSONException: No value for plus_code
> 
> remove plus_code

Or better yet, make it so that `parseDetailsData` in the `PlaceApi` class doesn't fail completely if there isn't a field there to parse. That way you can somewhat future-proof this in case the APIs change down the road.

**Comment by PriyankaRana-11** [comment]
json parsing issue: No value for plus_code .. still exists

**Comment by Bobbykart** [comment]
will it be fixed or can i delete this library from my project?

**Comment by bharathgrandhe-utu** [comment]
Happening for me too

**Comment by KhinThiriSoe** [comment]
I got this error too

**Comment by mukeshsolanki** [comment]
Fixed in the latest version

**Comment by gorv005** [comment]
org.json.JSONException: No value for vicinity
