### ISSUE TITLE
using this library sometimes places is getting and sometime not getting.why?

### ISSUE THREAD

**Issue by BhargaviSunku** [mukeshsolanki/Places-AutoComplete-EditText#15]
### Subject of the issue
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by hulisani-mudimeli** [comment]
It has to do with your billing for your google api key account
