### ISSUE TITLE
Very heavy CPU use, slows down app downloading map tiles when visible

### ISSUE THREAD

**Issue by kenargo** [mukeshsolanki/Places-AutoComplete-EditText#16]
### Subject of the issue
During the time that the widget is active, CPU use is very high

### Steps to reproduce
Open widget on UI surface

### Expected behaviour
The CPU use should be more inline with Google's widget

### Actual behaviour
UI is very slow to respond, loading map tiles while this widget is displayed, tile loading runs at a snails pace.  The same scenario, but using Google's widget is undetectable to UI response.

**Comment by mukeshsolanki** [comment]
@kenargo can you check again? also, can you check the sample app as well? I don't see it jumping in terms of CPU usage

**Comment by kenargo** [comment]
You can close for now; I've change to a different design so it might be some time before I get around to testing again.
