### ISSUE TITLE
What's the <latest-version> in build.gradle dependency? 

### ISSUE THREAD

**Issue by abhiejam** [mukeshsolanki/Places-AutoComplete-EditText#17]
I tried entering version of the app i.e. "1.0" as well as the latest version of Google places API. But neither did work. Would you mind telling me what should I enter in the <latest-version> @mukeshsolanki?
Thanks
```
dependencies {
        implementation 'com.github.mukeshsolanki:Google-Places-AutoComplete-EditText:**<latest-version>**'
}
```

**Comment by mukeshsolanki** [comment]
Please look at the readme file
