### ISSUE TITLE
Java code?

### ISSUE THREAD

**Issue by Luuk99** [mukeshsolanki/Places-AutoComplete-EditText#7]
Hi,

I was wondering if I can use your package with java?
I tried but got stuck at the PlaceAPI.builder part.

Is it supported and if so, could you provide the code?

Would be a big help, really looking to implement something like this instead of the usual AutoCompleteSupportFragment.

Thanks in advance.

**Comment by HassanDeveloper6** [comment]
Hi @Luuk99 !!
Have you found the solution for this?
I also tried with the java code but PlaceApi.Builder is not resolved.
Can you please help me?
